identity:
  protocol: DCCVALIDATION
  protocolVersion: 1.0.0
  #### serviceIdentity
  serviceIdentityUrl: https://validation-decorator.example
  consent: I want to check your DCC to confirm your booking! :)
  servicePovider: Service Provider.com
  restTemplate:
    connectionTimeout: 3000
    readTimeout: 3000

booking:
  urls:
    tokenContent: http://localhost:8082/tokencontent/{subject}
    result: http://localhost:8082/result/{subject}

#### Create Key: keytool -genkey -alias [ALIAS NAME] -keyalg EC -validity 3650 -keystore dev-decorator.jks -storetype JKS
dgc:
  #### Validation Decorator URI without trailing slash
  serviceUrl: http://localhost:8080
  keyStoreFile: certs/dev-decorator.jks
  keyStorePassword: changeMe
  privateKeyPassword: changeMe  
  activeSignKey: validationdecoratorsignkey
  encAliases: 
    - validationdecoratorenckey
  signAliases: 
    - validationdecoratorsignkey
  token:
    provider: config #### use "ks" (keyStore) or "config"
    issuer: Validation Decorator Dervice
    type: JWT
    algorithm: ES
    keysize: 256
    validity: 3600 #### in seconds. Expiration is calculated
    publicKey: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEIPrtYsW9+Juwp/mt7h8FJ3LgFRIUl2Vlmcl1DUm5gNHl0LnHIL4Jff6mg6yVhehdQiMvkhUtTvmFIUWONSJEnw==
    privateKey: MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCBSuPIbykwH24sjQsTneeN6EyjiA1NK5W7uca+HxmGmWw==
    keyAlgorithm: EC
  #### Validation Service
  services:
    - id: ${dgc.serviceUrl}/identity/ValidationService
      type: ValidationService
      serviceEndpoint: http://localhost:8081
      name: Validation Service
  #### Validation Decorator
  endpoints:
    - id: ${dgc.serviceUrl}/identity/AccessCredentialService
      type: AccessCredentialService
      serviceEndpoint: ${dgc.serviceUrl}/token
      name: Validation Decorator Token
    - id: ${dgc.serviceUrl}/identity/ServiceProvider
      type: ServiceProvider
      serviceEndpoint: ${dgc.serviceUrl}/identity
      name: Validation Decorator Identity
    - id: ${dgc.serviceUrl}/identity/CancellationService
      type: CancellationService
      serviceEndpoint: ${dgc.serviceUrl}/reject
      name: Validation Decorator Reject
    - id: ${dgc.serviceUrl}/identity/StatusService
      type: StatusService
      serviceEndpoint: ${dgc.serviceUrl}/status
      name: Validation Decorator Status

server:
  port: 8080

spring:
  application:
    name: dgca-validation-decorator
  profiles:
    active: keys

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: info,health

springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /swagger
