identity:
  protocol: DCCVALIDATION
  protocolVersion: 1.0.0
  #### serviceIdentity
  serviceIdentityUrl: https://serviceprovider/
  #### validationIdentity
  validationIdentityUrl: https://validation.serviceprovider/
  consent: I want to check your DCC to confirm your booking! :)
  servicePovider: Service Provider.com
  restTemplate:
    connectionTimeout: 3000
    readTimeout: 3000

booking:
  urls:
    boardingPass: http://localhost:8082/boardingpass/{subject}
    tokenContent: http://localhost:8082/tokencontent/{subject}

validation:
  urls:
    status: http://localhost:8081/status/{subject}

token:
  type: JWT
  algorithm: ES
  keysize: 256
  issuer: Validation Decorator Dervice
  validity: 3600 #### in seconds. Expiration is calculated
  publicKey: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEIPrtYsW9+Juwp/mt7h8FJ3LgFRIUl2Vlmcl1DUm5gNHl0LnHIL4Jff6mg6yVhehdQiMvkhUtTvmFIUWONSJEnw==
  privateKey: MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCBSuPIbykwH24sjQsTneeN6EyjiA1NK5W7uca+HxmGmWw==
  keyAlgorithm: EC

dgc:
  businessRulesDownload:
    timeInterval: 1800000
    lockLimit: 3600000
  certificatesDownloader:
    timeInterval: 1800000
    lockLimit: 3600000
  valueSetsDownload:
    timeInterval: 1800000
    lockLimit: 3600000
  serviceUrl: https://validation-service.de
  keyStoreFile: certs/dev-test.jks
  keyStorePassword: dcc
  privateKeyPassword: dcc

server:
  port: 8080

spring:
  application:
    name: dgca-validation-decorator
  profiles:
    active: keys

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: info,health

springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /swagger
