identity:
  protocol: DCCVALIDATION
  protocolVersion: 1.0.0
  #### serviceIdentity
  serviceIdentityUrl: https://validation-decorator.example
  consent: I want to check your DCC to confirm your booking! :)
  servicePovider: Service Provider.com
  restTemplate:
    connectionTimeout: 3000
    readTimeout: 3000

booking:
  urls:
    tokenContent: http://localhost:8082/tokencontent/{subject}
    result: http://localhost:8082/result/{subject}
    
#### Create Key: keytool -genkey -alias [ALIAS NAME] -keyalg EC -validity 3650 -keystore dev-decorator.jks -storetype JKS
dgc:
  serviceUrl: http://localhost:8080
  keyStoreFile: certs/dev-decorator.jks
  keyStorePassword: changeMe
  privateKeyPassword: changeMe  
  activeSignKey: validationdecoratorsignkey
  encAliases: 
    - validationdecoratorenckey
  signAliases: 
    - validationdecoratorsignkey
  keyAliases:
    - AccessTokenServiceKey-1
    - ServiceProviderKey-1 
    - CancellationServiceKey-1
    - StatusServiceKey-1
  token:
    issuer: Validation Decorator Dervice
    type: JWT
    initialize:
      validity: 3600 #### in seconds. Expiration is calculated
  services:
    #### Validation Service
    - id: http://localhost:8080/identity/ValidationService
      type: ValidationService
      serviceEndpoint: http://localhost:8081
      name: Validation Service
    #### Validation Decorator
    - id: http://localhost:8080/identity/AccessCredentialService
      type: AccessCredentialService
      serviceEndpoint: http://localhost:8080/token
      name: Validation Decorator Token
    - id: http://localhost:8080/identity/ServiceProvider
      type: ServiceProvider
      serviceEndpoint: http://localhost:8080/identity
      name: Validation Decorator Identity
    - id: http://localhost:8080/identity/CancellationService
      type: CancellationService
      serviceEndpoint: http://localhost:8080/reject
      name: Validation Decorator Reject
    - id: http://localhost:8080/identity/StatusService
      type: StatusService
      serviceEndpoint: http://localhost:8080/status
      name: Validation Decorator Status

server:
  port: 8080

spring:
  application:
    name: dgca-validation-decorator
  profiles:
    active: keys

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: info,health

springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /swagger
